package entity;
// Generated Aug 25, 2017 11:33:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kategorija generated by hbm2java
 */
@Entity
@Table(name="kategorija"
    ,catalog="ski_oprema"
)
public class Kategorija  implements java.io.Serializable {


     private Integer kategorijaId;
     private String kategorija;
     private Set<Proizvod> proizvods = new HashSet<Proizvod>(0);

    public Kategorija() {
    }

	
    public Kategorija(String kategorija) {
        this.kategorija = kategorija;
    }
    public Kategorija(String kategorija, Set<Proizvod> proizvods) {
       this.kategorija = kategorija;
       this.proizvods = proizvods;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="kategorija_id", unique=true, nullable=false)
    public Integer getKategorijaId() {
        return this.kategorijaId;
    }
    
    public void setKategorijaId(Integer kategorijaId) {
        this.kategorijaId = kategorijaId;
    }

    
    @Column(name="kategorija", nullable=false, length=45)
    public String getKategorija() {
        return this.kategorija;
    }
    
    public void setKategorija(String kategorija) {
        this.kategorija = kategorija;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="kategorija")
    public Set<Proizvod> getProizvods() {
        return this.proizvods;
    }
    
    public void setProizvods(Set<Proizvod> proizvods) {
        this.proizvods = proizvods;
    }




}


