package entity;
// Generated Aug 25, 2017 11:33:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Korisnik generated by hbm2java
 */
@Entity
@Table(name="korisnik"
    ,catalog="ski_oprema"
)
public class Korisnik  implements java.io.Serializable {


     private Integer korisnikId;
     private Prava prava;
     private String ime;
     private String prezime;
     private String email;
     private String sifra;
     private String adresa;
     private String grad;
     private Set<Porudzbina> porudzbinas = new HashSet<Porudzbina>(0);

    public Korisnik() {
    }

	
    public Korisnik(Prava prava, String ime, String prezime, String email, String sifra, String adresa, String grad) {
        this.prava = prava;
        this.ime = ime;
        this.prezime = prezime;
        this.email = email;
        this.sifra = sifra;
        this.adresa = adresa;
        this.grad = grad;
    }
    public Korisnik(Prava prava, String ime, String prezime, String email, String sifra, String adresa, String grad, Set<Porudzbina> porudzbinas) {
       this.prava = prava;
       this.ime = ime;
       this.prezime = prezime;
       this.email = email;
       this.sifra = sifra;
       this.adresa = adresa;
       this.grad = grad;
       this.porudzbinas = porudzbinas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="korisnik_id", unique=true, nullable=false)
    public Integer getKorisnikId() {
        return this.korisnikId;
    }
    
    public void setKorisnikId(Integer korisnikId) {
        this.korisnikId = korisnikId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pravo", nullable=false)
    public Prava getPrava() {
        return this.prava;
    }
    
    public void setPrava(Prava prava) {
        this.prava = prava;
    }

    
    @Column(name="ime", nullable=false, length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="prezime", nullable=false, length=45)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="sifra", nullable=false, length=45)
    public String getSifra() {
        return this.sifra;
    }
    
    public void setSifra(String sifra) {
        this.sifra = sifra;
    }

    
    @Column(name="adresa", nullable=false, length=45)
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }

    
    @Column(name="grad", nullable=false, length=45)
    public String getGrad() {
        return this.grad;
    }
    
    public void setGrad(String grad) {
        this.grad = grad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="korisnik")
    public Set<Porudzbina> getPorudzbinas() {
        return this.porudzbinas;
    }
    
    public void setPorudzbinas(Set<Porudzbina> porudzbinas) {
        this.porudzbinas = porudzbinas;
    }




}


