package entity;
// Generated Aug 25, 2017 11:33:04 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Porudzbina generated by hbm2java
 */
@Entity
@Table(name="porudzbina"
    ,catalog="ski_oprema"
)
public class Porudzbina  implements java.io.Serializable {


     private Integer porudzbinaId;
     private Korisnik korisnik;
     private Date datum;
     private Set<Stavka> stavkas = new HashSet<Stavka>(0);

    public Porudzbina() {
    }

	
    public Porudzbina(Korisnik korisnik, Date datum) {
        this.korisnik = korisnik;
        this.datum = datum;
    }
    public Porudzbina(Korisnik korisnik, Date datum, Set<Stavka> stavkas) {
       this.korisnik = korisnik;
       this.datum = datum;
       this.stavkas = stavkas;
    }

    public Porudzbina(Korisnik kor, String placena, int parseInt, String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="porudzbina_id", unique=true, nullable=false)
    public Integer getPorudzbinaId() {
        return this.porudzbinaId;
    }
    
    public void setPorudzbinaId(Integer porudzbinaId) {
        this.porudzbinaId = porudzbinaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="korisnik_id", nullable=false)
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datum", nullable=false, length=10)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="porudzbina")
    public Set<Stavka> getStavkas() {
        return this.stavkas;
    }
    
    public void setStavkas(Set<Stavka> stavkas) {
        this.stavkas = stavkas;
    }




}


