package entity;
// Generated Aug 25, 2017 11:33:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prava generated by hbm2java
 */
@Entity
@Table(name="prava"
    ,catalog="ski_oprema"
)
public class Prava  implements java.io.Serializable {


     private Integer pravaId;
     private String nazivPrava;
     private Set<Korisnik> korisniks = new HashSet<Korisnik>(0);
     
     public Prava(){}

    public Prava(int pravaId,String nazivPrava) {
        this.pravaId = pravaId;
        this.nazivPrava = nazivPrava;
    }

	
    public Prava(String nazivPrava) {
        this.nazivPrava = nazivPrava;
    }
    public Prava(String nazivPrava, Set<Korisnik> korisniks) {
       this.nazivPrava = nazivPrava;
       this.korisniks = korisniks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="prava_id", unique=true, nullable=false)
    public Integer getPravaId() {
        return this.pravaId;
    }
    
    public void setPravaId(Integer pravaId) {
        this.pravaId = pravaId;
    }

    
    @Column(name="naziv_prava", nullable=false, length=45)
    public String getNazivPrava() {
        return this.nazivPrava;
    }
    
    public void setNazivPrava(String nazivPrava) {
        this.nazivPrava = nazivPrava;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prava")
    public Set<Korisnik> getKorisniks() {
        return this.korisniks;
    }
    
    public void setKorisniks(Set<Korisnik> korisniks) {
        this.korisniks = korisniks;
    }




}


