package entity;
// Generated Aug 25, 2017 11:33:04 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proizvod generated by hbm2java
 */
@Entity
@Table(name="proizvod"
    ,catalog="ski_oprema"
)
public class Proizvod  implements java.io.Serializable {


     private Integer proizvodId;
     private Brend brend;
     private Kategorija kategorija;
     private String nazivProizvoda;
     private String referencuSlike;
     private BigDecimal cena;
     private String velicina;
     private String opis;
     private Set<Stavka> stavkas = new HashSet<Stavka>(0);

    public Proizvod() {
    }

	
    public Proizvod(Brend brend, Kategorija kategorija, String nazivProizvoda, String referencuSlike, BigDecimal cena, String velicina, String opis) {
        this.brend = brend;
        this.kategorija = kategorija;
        this.nazivProizvoda = nazivProizvoda;
        this.referencuSlike = referencuSlike;
        this.cena = cena;
        this.velicina = velicina;
        this.opis = opis;
    }
    public Proizvod(Brend brend, Kategorija kategorija, String nazivProizvoda, String referencuSlike, BigDecimal cena, String velicina, String opis, Set<Stavka> stavkas) {
       this.brend = brend;
       this.kategorija = kategorija;
       this.nazivProizvoda = nazivProizvoda;
       this.referencuSlike = referencuSlike;
       this.cena = cena;
       this.velicina = velicina;
       this.opis = opis;
       this.stavkas = stavkas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="proizvod_id", unique=true, nullable=false)
    public Integer getProizvodId() {
        return this.proizvodId;
    }
    
    public void setProizvodId(Integer proizvodId) {
        this.proizvodId = proizvodId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brend_id", nullable=false)
    public Brend getBrend() {
        return this.brend;
    }
    
    public void setBrend(Brend brend) {
        this.brend = brend;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="kategorija_id", nullable=false)
    public Kategorija getKategorija() {
        return this.kategorija;
    }
    
    public void setKategorija(Kategorija kategorija) {
        this.kategorija = kategorija;
    }

    
    @Column(name="naziv_proizvoda", nullable=false, length=45)
    public String getNazivProizvoda() {
        return this.nazivProizvoda;
    }
    
    public void setNazivProizvoda(String nazivProizvoda) {
        this.nazivProizvoda = nazivProizvoda;
    }

    
    @Column(name="referencu_slike", nullable=false, length=45)
    public String getReferencuSlike() {
        return this.referencuSlike;
    }
    
    public void setReferencuSlike(String referencuSlike) {
        this.referencuSlike = referencuSlike;
    }

    
    @Column(name="cena", nullable=false, precision=9)
    public BigDecimal getCena() {
        return this.cena;
    }
    
    public void setCena(BigDecimal cena) {
        this.cena = cena;
    }

    
    @Column(name="velicina", nullable=false, length=100)
    public String getVelicina() {
        return this.velicina;
    }
    
    public void setVelicina(String velicina) {
        this.velicina = velicina;
    }

    
    @Column(name="opis", nullable=false, length=500)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proizvod")
    public Set<Stavka> getStavkas() {
        return this.stavkas;
    }
    
    public void setStavkas(Set<Stavka> stavkas) {
        this.stavkas = stavkas;
    }




}


