package entity;
// Generated Aug 25, 2017 11:33:04 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stavka generated by hbm2java
 */
@Entity
@Table(name="stavka"
    ,catalog="ski_oprema"
)
public class Stavka  implements java.io.Serializable {


     private Integer stavkaId;
     private Porudzbina porudzbina;
     private Proizvod proizvod;
     private int kolicina;

    public Stavka() {
    }

    public Stavka(Porudzbina porudzbina, Proizvod proizvod, int kolicina) {
       this.porudzbina = porudzbina;
       this.proizvod = proizvod;
       this.kolicina = kolicina;
    }
    
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="stavka_id", unique=true, nullable=false)
    public Integer getStavkaId() {
        return this.stavkaId;
    }
    
    public void setStavkaId(Integer stavkaId) {
        this.stavkaId = stavkaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="porudzbina_id", nullable=false)
    public Porudzbina getPorudzbina() {
        return this.porudzbina;
    }
    
    public void setPorudzbina(Porudzbina porudzbina) {
        this.porudzbina = porudzbina;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proizvod_id", nullable=false)
    public Proizvod getProizvod() {
        return this.proizvod;
    }
    
    public void setProizvod(Proizvod proizvod) {
        this.proizvod = proizvod;
    }

    
    @Column(name="kolicina", nullable=false)
    public int getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(int kolicina) {
        this.kolicina = kolicina;
    }




}


